import React, { useCallback, useEffect, useState } from 'react';
import Card from './Card';
import type { PlaidLinkOptions } from '../types';

interface ConnectBankProps {
    onConnected: () => void;
}

const ConnectBank: React.FC<ConnectBankProps> = ({ onConnected }) => {
    // In a real application, you would fetch a link_token from your server.
    // This token is temporary and is used to initialize the Plaid Link UI.
    const [linkToken, setLinkToken] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(true);

    // This callback is invoked when the user successfully authenticates.
    const onSuccess = useCallback((public_token: string) => {
        // The public_token is a temporary, one-time-use token.
        // You would send this to your server to exchange it for a permanent access_token.
        // e.g., await fetch('/api/plaid/exchange_public_token', { method: 'POST', body: JSON.stringify({ public_token }) });
        
        // After your server confirms the exchange, you can mark the bank as connected.
        console.log("Successfully received public_token:", public_token);
        alert("Bank connection successful! In a real app, data would now be synced from your bank.");
        
        // We'll add a small delay to simulate the final step and then navigate.
        setTimeout(() => {
            onConnected();
        }, 1500);

    }, [onConnected]);

    // This simulates fetching the link_token from your backend on component mount.
    useEffect(() => {
        const getLinkToken = async () => {
            // In a real app, you'd make a call to your secure server.
            // e.g., const response = await fetch('/api/plaid/create_link_token');
            // const data = await response.json();
            // setLinkToken(data.link_token);
            
            // For demonstration, we'll acknowledge that this token must be generated by a server
            // and cannot be created on the client-side for security reasons.
            console.warn("This is a demonstration. A real link_token must be generated by a server to initialize Plaid Link.");
            setIsLoading(false);
            // In a real scenario, you would uncomment the line below after fetching the token.
            // setLinkToken('a-real-token-from-your-server');
        };
        getLinkToken();
    }, []);

    const openPlaidLink = () => {
        if (!window.Plaid) {
            alert("Plaid SDK not loaded. Please check your internet connection.");
            return;
        }

        if (!linkToken) {
            alert("Could not initialize banking connection. The link_token is missing. In a real application, this would be generated by a secure server and fetched by the client.");
            return;
        }

        const handler = window.Plaid.create({
            token: linkToken,
            onSuccess: onSuccess,
        });

        handler.open();
    };

    return (
        <div>
            <h2 className="text-3xl font-bold text-slate-800">Connect Bank Account</h2>
            <Card className="mt-6 max-w-2xl mx-auto">
                <div className="text-center">
                    <img src="https://cdn.plaid.com/brand/logo-blue.svg" alt="Plaid Logo" className="h-8 mx-auto mb-4" />
                    <h3 className="text-xl font-bold text-slate-800 mb-2">Securely Connect Your Bank</h3>
                    <p className="text-slate-600 mb-6">
                        FinanSage partners with Plaid to securely link your UK financial accounts. Your credentials are encrypted and are never shared with us.
                    </p>
                    {isLoading ? (
                         <button className="w-full bg-slate-300 text-white py-3 rounded-lg font-semibold cursor-not-allowed flex items-center justify-center">
                            <i className="fas fa-spinner fa-spin mr-2"></i> Initializing Connection...
                        </button>
                    ) : (
                        <button 
                            onClick={openPlaidLink} 
                            disabled={!linkToken} // Button is disabled because we can't generate a linkToken
                            className="w-full bg-sky-500 text-white py-3 rounded-lg font-semibold hover:bg-sky-600 transition-colors disabled:bg-slate-400 disabled:cursor-not-allowed"
                        >
                            <i className="fas fa-university mr-2"></i> Connect with Plaid
                        </button>
                    )}
                    {!linkToken && !isLoading && (
                        <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg text-amber-800 text-sm">
                            <p><strong>Demonstration Mode:</strong> To launch the Plaid modal, a `link_token` must be generated by a secure backend server. This button is currently disabled because there is no backend configured.</p>
                        </div>
                    )}
                </div>
            </Card>
        </div>
    );
};

export default ConnectBank;
